apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deploy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bank-app
      type: backend
  template:
    metadata:
      labels:
        app: bank-app
        type: backend
    spec:
      containers:
      - name: backend-app
        image: prajapatdip/bank-app-backend:latest
        ports:
        - containerPort: 3001
        env:
        - name: APP_PORT
          valueFrom:
            configMapKeyRef:
              name: app-config
              key: backend-url
        - name: JWT_SECRET
          valueFrom:
            secretKeyRef:
              name: mysecret
              key: JWTSECRET
        - name: DB_USER
          valueFrom:
            secretKeyRef:
              name: mysecret
              key: USERNAME
        - name: DB_PASS
          valueFrom:
            secretKeyRef:
              name: mysecret
              key: PASSWORD
        - name: DB_HOST
          valueFrom:
            secretKeyRef:
              name: mysecret
              key: HOSTNAME
        - name: DB_PORT
          valueFrom:
            configMapKeyRef:
              name: app-config
              key: postgres-url

---

apiVersion: v1
kind: Service
metadata:
  name: backend-service
spec:
  selector:
    app: bank-app
    type: backend
  ports:
  - protocol: TCP
    port: 3001
    targetPort: 3001