apiVersion: apps/v1
kind: Deployment
metadata:
  name: db-deploy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bank-app
      type: db
  template:
    metadata:
      labels:
        app: bank-app
        type: db
    spec:
      containers:
      - name: postgres
        image: postgres:15.1
        ports:
        - containerPort: 8080
        env:
        - name: POSTGRES_USER
          valueFrom:
            secretKeyRef:
              name: mysecret
              key: USERNAME
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysecret
              key: PASSWORD

---

apiVersion: v1
kind: Service
metadata:
  name: db-service
spec:
  selector:
    app: bank-app
    type: db
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080