apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-deploy
spec:
  selector:
    matchLabels:
      app: bank-app
      type: frontend
  replicas: 3
  template:
    metadata:
      labels:
        app: bank-app
        type: frontend
    spec:
      containers:
      - name: frontend-app
        image: prajapatdip/bank-app-frontend:latest
        ports:
        - containerPort: 3000
        env:
        - name: NEXT_PUBLIC_API_URL
          valueFrom:
            configMapKeyRef:
              name: app-config
              key: frontend-url

---

apiVersion: v1
kind: Service
metadata:
  name: frontend-service
spec:
  selector:
    app: bank-app
    type: frontend
  type: NodePort
  ports:
  - protocol: TCP
    port: 3000
    targetPort: 3000
    nodePort: 30000
